# -*- coding: utf-8 -*-
"""HubSpot Data Enrichment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y8pALf0IwFaU8IcnazoGyOKzuOAV-X_h
"""

import requests
import json

def main(event, callback):
    api_key = " "
    url = "https://api.apollo.io/v1/people/match"

    # Get inputs from event
    first_name = event["inputFields"]["firstname"]
    last_name = event["inputFields"]["lastname"]
    domain = event["inputFields"]["domain"]
    email = event["inputFields"]["email"]

    # Create request body
    data = {
        "api_key": api_key,
        "name": f"{first_name} {last_name}",
        "email": email,
        "domain": domain,
    }

    # Create headers
    headers = {
        "Content-Type": "application/json",
        "Cache-Control": "no-cache",
    }

    # Make request
    response = requests.post(url, headers=headers, data=json.dumps(data))

    phone = None
    if response.status_code == 200:
        res = response.json()

        # Check if the `contact` key exists in the `person` dictionary
        if "contact" in res["person"]:
            # Check if the `sanitized_number` key exists in the `phone_numbers` list
            if res["person"]["contact"]["phone_numbers"]:
                phone = res["person"]["contact"]["phone_numbers"][0]["sanitized_number"]

    # Call the callback function
    callback({"outputFields": {"phone": phone}})

if __name__ == "__main__":
    main(
        event={
            "inputFields": {
                "firstname": "John",
                "lastname": "Doe",
                "domain": "example.com",
                "email": "john.doe@example.com",
            }
        },
        callback=lambda output: print(output),
    )